export { default as HomePage } from "../pages/Home"
export { default as SearchBar } from "../components/Headers/SecondHeader"
export { default as Headers } from "../components/Headers/TopHeader"
export { default as HeaderLinks } from "../components/Headers/ThirdHeader"
export { default as SliderBg } from "../components/slider/Sliderlg"
export { default as SliderSm } from "../components/slider/Sliders"
export { default as Service } from "../components/services/Services"
export { default as Footer } from "../components/Footer"